language: python

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      env:
        - LUA="lua=5.1"
        - LUA_CJSON=""
    - os: linux
      env:
        - LUA="lua=5.2"
        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="lua=5.3"
        - LUA_CJSON="2.1.0"
#    - os: linux
#      env:
#        - LUA="lua=5.4"
#        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="luajit=2.0"
        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="luajit=2.1"
        - LUA_CJSON=""

install:
  - pip install codecov
  - pip install hererocks
  - hererocks lua_install --$LUA -r latest
  - source lua_install/bin/activate
  - .travis/before.sh

script:
  - busted -c

after_script:
  - luacov
  - codecov -X gcov