language: python

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      env:
        - LUA="lua=5.1"
        - LUA_CJSON=""
    - os: linux
      env:
        - LUA="lua=5.2"
        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="lua=5.3"
        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="lua=5.4"
        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="luajit=2.0"
        - LUA_CJSON="2.1.0"
    - os: linux
      env:
        - LUA="luajit=2.1"
        - LUA_CJSON=""

before_install:
  - pip install codecov
  - pip install hererocks
  - hererocks lua_install --$LUA -r latest
  - source lua_install/bin/activate
  - luarocks install busted
  - lua -e 'if _VERSION ~= "Lua 5.4" then os.exit(1) else os.exit(0) end' && luarocks install cluacov; exit 0 # cluacov doesn't work on 5.4
  - luarocks install lua-cjson $LUA_CJSON
  - lua -e 'if utf8 then os.exit(1) else os.exit(0) end' && luarocks install utf8; exit 0 # lua 5.3+ already has utf8 module

script:
  - busted -c

after_script:
  - luacov
  - codecov -X gcov