title: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT."
encoding: UTF-8
markdown: kramdown
url: "https://aspect.unifire.app"
exclude:
  - src
  - bin
theme: jekyll-theme-dinky
google_analytics: UA-164241665-1
logo: /assets/aspect.png
#canonical_url: "https://github.com/unifire-app/aspect"
image:
  path: /assets/aspect.png
  height: 100
  width: 100