title: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT."
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io"
exclude:
  - src
  - bin
theme: jekyll-theme-slate
show_downloads: true
google_analytics: UA-164241665-1