name: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT (OpenResty, Tarantool) with syntax Twig/Jinja/Django/Liquid."
encoding: UTF-8
markdown: kramdown
url: "https://aspect.unifire.app"
exclude:
  - src
  - bin
theme: jekyll-theme-slate