name: Testing the GitHub Pages publication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    
    # Standard usage
    - uses:  helaili/jekyll-action@2.0.0
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_PAT }}
    
    # Specify the Jekyll source location as a parameter
    - uses: helaili/jekyll-action@2.0.0
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_PAT }}
      with:
        jekyll_src: 'sample_site'
