name: Jekyll Deploy

on:
  push:
    branches:
    - master

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: jekyll-deploy-gh-pages
        uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
